### ISSUE TITLE
Can't run in the latest Win11 Beta 无法运行在最新的Win11 Beta

### ISSUE THREAD

**Issue by KeeLee2005** [garyan2/wmcsetup#1]
After an update, cannot install kb3106246, installed program kb3106246 will be removed, causing WMC unable to open.
在一次更新后不能安装kb3106246，已安装的kb3106246将被移除，导致WMC无法打开。

_(The above English is machine [translation)（上述英语为机器翻译）_

- OS: [Windows 11 Insider Preview Build22621.1]

**Comment by KeeLee2005** [comment]
源
Windows Media Center

摘要
已停止工作

日期
‎2022/‎6/‎6 22:35

状态
已发送报告

描述
错误的应用程序路径:	C:\Program Files\Windows Media Center\ehome\ehshell.exe

问题签名
问题事件名称:	APPCRASH
应用程序名:	ehshell.exe
应用程序版本:	6.3.9600.16384
应用程序时间戳:	5215efc2
故障模块名称:	KERNELBASE.dll
故障模块版本:	10.0.22621.1
故障模块时间戳:	ec07489e
异常代码:	e0434352
异常偏移:	000000000008fa7c
OS 版本:	10.0.22621.2.0.0.256.48
区域设置 ID:	2052
其他信息 1:	7880
其他信息 2:	78801219e2a3bd1b7d1b720d01711ebd
其他信息 3:	e7be
其他信息 4:	e7bedbd5a8160738f642649bf021958e

关于该问题的额外信息
存储段 ID:	753845234bbedad3f2b0a9f5a34eeb29 (1346763161055718185)

**Comment by garyan2** [comment]
I have installed WMC on the beta version of Win11 without issue. It was an update though and I haven't tried a fresh install of Win11 to see if there are any problems yet.

I hope this translates well, but I did see that if a language pack is installed after the DVD Player was installed, you will need to uninstall the DVD Player and install it again. This may be a part of your problem.

**Comment by KeeLee2005** [comment]
> I have installed WMC on the beta version of Win11 without issue. It was an update though and I haven't tried a fresh install of Win11 to see if there are any problems yet.
> 
> I hope this translates well, but I did see that if a language pack is installed after the DVD Player was installed, you will need to uninstall the DVD Player and install it again. This may be a part of your problem.

But how to open WMC without the DVD Player(kb3106246)? The DVD Player was removed in the previous update and I am unable to reinstall it.

**Comment by garyan2** [comment]
The only reason I know of that the KB won't install is a registry entry. Open the registry and find the key **\\HKLM\SYSTEM\CurrentControlSet\Services\ADOVMPPackage\Final**, set "ActivationEnabled" to DWORD:0x00000002. If that is already set to '2', then I don't know why it is not installing for you. Let me know if it still is not working for you and I can try to find what I can do here.

**Comment by KeeLee2005** [comment]
> The only reason I know of that the KB won't install is a registry entry. Open the registry and find the key **\HKLM\SYSTEM\CurrentControlSet\Services\ADOVMPPackage\Final**, set "ActivationEnabled" to DWORD:0x00000002. If that is already set to '2', then I don't know why it is not installing for you. Let me know if it still is not working for you and I can try to find what I can do here.

No matter how I experimented, WMC never worked in my PC. I'll still run WMC in a virtual machine, Windows has changed a lot. Thanks to the developers for their contributions. (machine translation)

**Comment by KeeLee2005** [comment]
The software seems to be available again in the new beta windows. Microsoft changed something in the beta window a while ago and caused problems with some programs.

**Comment by FeizaiGameExplanation** [comment]
![Image](https://github.com/user-attachments/assets/298dc5a7-a75f-43e1-9808-df1072de9e06)
win10可以，win11就不行。给个帮助
