### ISSUE TITLE
Downloading TV Setup data seems to hang

### ISSUE THREAD

**Issue by DevelopCMD** [garyan2/wmcsetup#2]
Whenever it downloads the setup data, for some reason, it seems like it's hanging. Why is it doing that?

**Comment by garyan2** [comment]
Because it is trying to connect to the Microsoft servers that no longer exist. Change your "Always On" Internet connection to 'No' before running TV Setup. https://garyan2.github.io/win10.html

Scroll down the page to see where the setting is within WMC.
